src/ClanmanagerBundle/Entity/War.php
<?php

namespace ClanmanagerBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * War
 *
 * @ORM\Table(name="War")
 * @ORM\Entity(repositoryClass="ClanmanagerBundle\Entity\WarRepository")
 */
class War {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var datetime
     *
     * @ORM\Column(name="start", type="datetime")
     */
    private $start;

    /**
     * @var integer
     *
     * @ORM\Column(name="size", type="integer")
     */
    private $size;

    /**
     * @ORM\OneToMany(targetEntity="Warclan", mappedBy="war")
     */
    protected $warclans;

    public function __construct() {
        $this->warclans = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set start
     *
     * @param \DateTime $start
     * @return War
     */
    public function setStart($start) {
        $this->start = $start;

        return $this;
    }

    /**
     * Get start
     *
     * @return \DateTime 
     */
    public function getStart() {
        return $this->start;
    }

    /**
     * Set size
     *
     * @param integer $size
     * @return War
     */
    public function setSize($size) {
        $this->size = $size;

        return $this;
    }

    /**
     * Get size
     *
     * @return integer 
     */
    public function getSize() {
        return $this->size;
    }

    /**
     * Add warclans
     *
     * @param \ClanmanagerBundle\Entity\Warclan $warclans
     * @return War
     */
    public function addWarclan(\ClanmanagerBundle\Entity\Warclan $warclans) {
        $this->warclans[] = $warclans;

        return $this;
    }

    /**
     * Remove warclans
     *
     * @param \ClanmanagerBundle\Entity\Warclan $warclans
     */
    public function removeWarclan(\ClanmanagerBundle\Entity\Warclan $warclans) {
        $this->warclans->removeElement($warclans);
    }

    /**
     * Get warclans
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getWarclans() {
        return $this->warclans;
    }

    public function __toString() {
        return $this->getId() . " " . $this->getWarClans()[0]->getClan()->getName() . " - " . $this->getWarClans()[1]->getClan()->getName();
    }

}

src/ClanmanagerBundle/Entity/Warclan.php
<?php

namespace ClanmanagerBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Warclan
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="ClanmanagerBundle\Entity\WarclanRepository")
 */
class Warclan {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var integer
     *
     * @ORM\Column(name="wins", type="integer")
     */
    private $wins;

    /**
     * @var integer
     *
     * @ORM\Column(name="stars", type="integer", nullable=true)
     */
    private $stars;

     /**
     * @var float
     *
     * @ORM\Column(name="percent", type="float", nullable=true)
     */
    private $percent;

    /**
     * @ORM\ManyToOne(targetEntity="Clan", inversedBy="warclans")
     * @ORM\JoinColumn(name="clan_id", referencedColumnName="id")
     */
    protected $clan;

    /**
     * @ORM\ManyToOne(targetEntity="War", inversedBy="warclans")
     * @ORM\JoinColumn(name="war_id", referencedColumnName="id")
     */
    protected $war;

    /**
     * @ORM\OneToMany(targetEntity="Warplayer", mappedBy="warclan")
     */
    protected $warplayers;

    /**
     * Constructor
     */
    public function __construct() {
        $this->warplayers = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set clan
     *
     * @param \ClanmanagerBundle\Entity\Clan $clan
     * @return Warclan
     */
    public function setClan(\ClanmanagerBundle\Entity\Clan $clan = null) {
        $this->clan = $clan;

        return $this;
    }

    /**
     * Get clan
     *
     * @return \ClanmanagerBundle\Entity\Clan 
     */
    public function getClan() {
        return $this->clan;
    }

    /**
     * Set war
     *
     * @param \ClanmanagerBundle\Entity\War $war
     * @return Warclan
     */
    public function setWar(\ClanmanagerBundle\Entity\War $war = null) {
        $this->war = $war;

        return $this;
    }

    /**
     * Get war
     *
     * @return \ClanmanagerBundle\Entity\War 
     */
    public function getWar() {
        return $this->war;
    }

    /**
     * Add warplayers
     *
     * @param \ClanmanagerBundle\Entity\Warplayer $warplayers
     * @return Warclan
     */
    public function addWarplayer(\ClanmanagerBundle\Entity\Warplayer $warplayers) {
        $this->warplayers[] = $warplayers;

        return $this;
    }

    /**
     * Remove warplayers
     *
     * @param \ClanmanagerBundle\Entity\Warplayer $warplayers
     */
    public function removeWarplayer(\ClanmanagerBundle\Entity\Warplayer $warplayers) {
        $this->warplayers->removeElement($warplayers);
    }

    /**
     * Get warplayers
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getWarplayers() {
        return $this->warplayers;
    }

    /**
     * Set wins
     *
     * @param integer $wins
     * @return Warclan
     */
    public function setWins($wins) {
        $this->wins = $wins;

        return $this;
    }

    /**
     * Get wins
     *
     * @return integer 
     */
    public function getWins() {
        return $this->wins;
    }

    /**
     * Get nr of Attacks
     * 
     * returns the number of attacks made by this warclan.
     *
     * @return integer 
     */
    public function getNrattacks() {
        $nrattacks = 0;
        foreach ($this->getWarplayers() as $warplayer) {
            $nrattacks += sizeof($warplayer->getAttacks());
        }
        return $nrattacks;
    }

    /**
     * Get Stars
     * 
     * returns the number of stars suffered by this warclan.
     *
     * @return integer 
     */
    public function getStars() {
        return $this->stars;
    }

    public function getTimestars() {
        $totalstars = array(0);
        for ($hour = 0; $hour < 24; $hour++) {
            $nrstars = 0;
            foreach ($this->getWarplayers() as $warplayer) {
                $stars = array(0);
                foreach ($warplayer->getDefends() as $warevent) {
                    if (date_format($warevent->getTime(), "H") >= $hour) {
                        $stars[] = $warevent->getStars();
                    }
                }
                $nrstars += max($stars);
            }
            $totalstars[$hour] = $nrstars;
        }
        return $totalstars;
    }

    public function getNrTH($th) {
        $nr = 0;
        foreach ($this->getWarplayers() as $warplayer) {
            if ($warplayer->getTh() == $th)
                $nr++;
        }
        return $nr ? $nr : "-";
    }

    public function getTimeattacks() {
        $totalattacks = array(0);
        for ($hour = 0; $hour < 24; $hour++) {
            $nrattacks = 0;
            foreach ($this->getWarplayers() as $warplayer) {
                $attacks = 0;
                foreach ($warplayer->getDefends() as $warevent) {
                    if (date_format($warevent->getTime(), "H") >= $hour) {
                        $attacks += 1;
                    }
                }
                $nrattacks += $attacks;
            }
            $totalattacks[$hour] = $nrattacks;
        }
        return $totalattacks;
    }

    /**
     * Set stars
     *
     * @param integer $stars
     * @return Warclan
     */
    public function setStars($stars) {
        $this->stars = $stars;

        return $this;
    }


    /**
     * Set percent
     *
     * @param float $percent
     * @return Warclan
     */
    public function setPercent($percent)
    {
        $this->percent = $percent;

        return $this;
    }

    /**
     * Get percent
     *
     * @return float 
     */
    public function getPercent()
    {
        return $this->percent;
    }
}

src/ClanmanagerBundle/Entity/Warplayer.php
<?php

namespace ClanmanagerBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Warplayer
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="ClanmanagerBundle\Entity\WarplayerRepository")
 */
class Warplayer {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var integer
     *
     * @ORM\Column(name="rank", type="integer", nullable=true)
     */
    private $rank;

    /**
     * @var integer
     *
     * @ORM\Column(name="th", type="integer", nullable=true)
     */
    private $th;

     /**
     * @var integer
     *
     * @ORM\Column(name="netstars", type="integer", nullable=true)
     */
    private $netstars;

    /**
     * @ORM\ManyToOne(targetEntity="Player", inversedBy="warplayers")
     * @ORM\JoinColumn(name="player_id", referencedColumnName="id")
     */
    protected $player;

    /**
     * @ORM\ManyToOne(targetEntity="Warclan", inversedBy="warplayers")
     * @ORM\JoinColumn(name="warclan_id", referencedColumnName="id")
     */
    protected $warclan;

    /**
     * @ORM\OneToMany(targetEntity="Warevent", mappedBy="attacker")
     */
    protected $attacks;

    /**
     * @ORM\OneToMany(targetEntity="Warevent", mappedBy="defender")
     */
    protected $defends;

    /**
     * Constructor
     */
    public function __construct() {
        $this->attacks = new \Doctrine\Common\Collections\ArrayCollection();
        $this->defends = new \Doctrine\Common\Collections\ArrayCollection();
        //$this->warplayers = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set player
     *
     * @param \ClanmanagerBundle\Entity\Player $player
     * @return Warplayer
     */
    public function setPlayer(\ClanmanagerBundle\Entity\Player $player = null) {
        $this->player = $player;

        return $this;
    }

    /**
     * Get player
     *
     * @return \ClanmanagerBundle\Entity\Player 
     */
    public function getPlayer() {
        return $this->player;
    }

    /**
     * Set rank
     *
     * @param integer $rank
     * @return Warplayer
     */
    public function setRank($rank) {
        $this->rank = $rank;

        return $this;
    }

    /**
     * Get rank
     *
     * @return integer 
     */
    public function getRank() {
        return $this->rank;
    }

    /**
     * Set th
     *
     * @param integer $th
     * @return Warplayer
     */
    public function setTh($th) {
        $this->th = $th;

        return $this;
    }

    /**
     * Get th
     *
     * @return integer 
     */
    public function getTh() {
        return $this->th;
    }

    /**
     * Set warclan
     *
     * @param \ClanmanagerBundle\Entity\Warclan $warclan
     * @return Warplayer
     */
    public function setWarclan(\ClanmanagerBundle\Entity\Warclan $warclan = null) {
        $this->warclan = $warclan;

        return $this;
    }

    /**
     * Get warclan
     *
     * @return \ClanmanagerBundle\Entity\Warclan 
     */
    public function getWarclan() {
        return $this->warclan;
    }

    /**
     * Add attacks
     *
     * @param \ClanmanagerBundle\Entity\Warevent $attacks
     * @return Warplayer
     */
    public function addAttack(\ClanmanagerBundle\Entity\Warevent $attacks) {
        $this->attacks[] = $attacks;

        return $this;
    }

    /**
     * Remove attacks
     *
     * @param \ClanmanagerBundle\Entity\Warevent $attacks
     */
    public function removeAttack(\ClanmanagerBundle\Entity\Warevent $attacks) {
        $this->attacks->removeElement($attacks);
    }

    /**
     * Get attacks
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getAttacks() {
        return $this->attacks;
    }

    /**
     * Add defends
     *
     * @param \ClanmanagerBundle\Entity\Warevent $defends
     * @return Warplayer
     */
    public function addDefend(\ClanmanagerBundle\Entity\Warevent $defends) {
        $this->defends[] = $defends;

        return $this;
    }

    /**
     * Remove defends
     *
     * @param \ClanmanagerBundle\Entity\Warevent $defends
     */
    public function removeDefend(\ClanmanagerBundle\Entity\Warevent $defends) {
        $this->defends->removeElement($defends);
    }

    /**
     * Get defends
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getDefends() {
        return $this->defends;
    }

    public function __toString() {
        if ($this->getPlayer())
            return $this->getRank() . ". " . $this->getPlayer()->getName(); // . " - " . $this->getId();
        else
            return $this->getRank() . ". ---";
    }

    /**
     * Get Stars
     * 
     * returns the number of stars suffered by this warplayer.
     *
     * @return integer 
     */
    public function getStars($time = NULL) {
        $nrstars = 0;
        $stars = array(0);
        foreach ($this->getDefends() as $warevent) {
            if ($warevent->getTime() > $time) //new \DateTime("23:10"))
                $stars[] = $warevent->getStars();
        }
        $nrstars += max($stars);
        return $nrstars;
    }

    /**
     * Get Bestattack
     * 
     * returns the best attack suffered by this warplayer.
     *
     * @return \ClanmanagerBundle\Entity\Warevent 
     */
    public function getBestattack() {
        $warevents = $this->getDefends()->toArray();

        if (sizeof($warevents)) {
            
            usort($warevents, function($b, $a) {
                if ($a->getStars() == $b->getStars()) {
                    if ($a->getPercent() > $b->getPercent()) {
                        return 1;
                    } elseif ($a->getPercent() < $b->getPercent()) {
                        return -1;
                    } else {
                        return 0;
                    }
                } elseif ($a->getStars() > $b->getStars()) {
                    return 1;
                } elseif ($a->getStars() < $b->getStars()) {
                    return -1;
                } else {
                    return 0;
                }
            });
            
            // first is best
            return $warevents[0];
        } else {
            return NULL;
        }
    }


    /**
     * Set netstars
     *
     * @param integer $netstars
     * @return Warplayer
     */
    public function setNetstars($netstars)
    {
        $this->netstars = $netstars;

        return $this;
    }

    /**
     * Get netstars
     *
     * @return integer 
     */
    public function getNetstars()
    {
        return $this->netstars;
    }
}

src/ClanmanagerBundle/Resources/views/War/new.html.twig
{% extends 'ClanmanagerBundle::base.html.twig' %}

{% block title %}CoC ClanManager{% endblock %}

{% block body %}

    <h1>New War</h1>

    <table>
        {{ form_start(form) }}
        <tr>
            <td>Start</td>
            <td>{{ form_widget(form.start) }}</td>
        <tr>
        <tr>
            <td>Size</td>
            <td>{{ form_widget(form.size) }}</td>
        <tr>
        <tr>
            <td>enemy clantag</td>
            <td>{{ form_widget(form.clantag) }}</td>
        </tr>
        <tr>
            <td>enemy clanname</td>
            <td>{{ form_widget(form.clanname) }}</td>
        </tr>
        <tr>
            <td>enemy wins</td>
            <td>{{ form_widget(form.clanwins) }}</td>
        </tr>
        <tr>
            <td>myclan wins</td>
            <td>{{ form_widget(form.myclanwins) }}</td>
        </tr>
        <tr>
            <td></td>
            <td>{{ form_widget(form.save) }}</td>
        </tr>
        <td>{{ form_end(form) }}</td>
    </tr>
</table>
{% endblock %}

src/ClanmanagerBundle/Resources/views/War/view.html.twig
{% extends 'ClanmanagerBundle::base.html.twig' %}

{% block title %}CoC ClanManager{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('css/war.css') }}" rel="stylesheet" />
{% endblock %}

{% block body %}

    <table>
        <tr>
            <th>{{ war.id }}.</th>
            <th colspan="10">{#{{ war.warclans[0].id }}. #}{{ war.warclans[0].clan.name }} ({{ war.warclans[0].wins }}) {{ war.warclans[0].nrattacks }}/{{ war.size*2 }} {# war.warclans[1].stars #} {{ render(controller('ClanmanagerBundle:Warclan:percent',{ 'warclan_id': war.warclans[1].id } ))|number_format(2) }}% <img height="14px" src="{{ asset('images/star.png') }}">{{ render(controller('ClanmanagerBundle:Warclan:stars',{ 'warclan_id': war.warclans[1].id } )) }}</th>
            <th></th>
            <th colspan="10">{#{{ war.warclans[1].id }}. #}{{ war.warclans[1].clan.name }} ({{ war.warclans[1].wins }}) {{ war.warclans[1].nrattacks }}/{{ war.size*2 }} {# war.warclans[0].stars #} {{ render(controller('ClanmanagerBundle:Warclan:percent',{ 'warclan_id': war.warclans[0].id } ))|number_format(2) }}% <img height="14px" src="{{ asset('images/star.png') }}">{{ render(controller('ClanmanagerBundle:Warclan:stars',{ 'warclan_id': war.warclans[0].id } )) }}</th>
        </tr>

        {% for rank in 1 .. war.size %}
            <tr>

                <td>&nbsp;{{ "%+d"|format(players[rank-1].netstars) }}&nbsp;{{ players[rank-1].offenseweight|number_format }}</td>                    

                {% for wc in 0..1 %}
                    <td class="attacker">{{ rank }}. {{ wc==0 and players[rank-1].offenserank is defined ? ["(",players[rank-1].offenserank,")"]|join :"" }}</td>


                    <td class="attacker">
                        <a href="{{ war.warclans[wc].warplayers[rank-1].player is defined and app.user and is_granted('ROLE_ADMIN') ? path('warplayer_edit',{'warplayer_id':war.warclans[wc].warplayers[rank-1].id} ) : '#' }}">
                            {{ war.warclans[wc].warplayers[rank-1].player.name is defined ? war.warclans[wc].warplayers[rank-1].player.name : "---" }}
                        </a>
                    </td>
                    <td class="attacker">
                        {% if war.warclans[wc].warplayers[rank-1] is defined %}
                            TH{{ war.warclans[wc].warplayers[rank-1].th }}
                        {% endif %}
                    </td>


                    <td>&nbsp;</td>        

                    <td>
                        {% if war.warclans[wc].warplayers[rank-1].defends is defined and war.warclans[wc].warplayers[rank-1].defends|length %}
                            <img height="10px" src="{{  asset( ['images/',war.warclans[wc].warplayers[rank-1].bestattack.stars,'star.png']|join ) }}" 
                                 xtitle="{{ war.warclans[wc].warplayers[rank-1].bestattack.time|date('H:i') }} {{ war.warclans[wc].warplayers[rank-1].bestattack.attacker.player.name }} {{ war.warclans[wc].warplayers[rank-1].bestattack.percent }}%"
                                 title="
{% for defend in war.warclans[wc].warplayers[rank-1].defends %}
{{ defend.time|date('H:i') }} {{ defend.attacker.player.name }} *{{ defend.stars }} {{ defend.percent }}%
{% endfor %}
                                 "
                                 >
                        {% endif %}
                    </td>
                    <td class="attacker">
                        {% if war.warclans[wc].warplayers[rank-1].defends is defined and war.warclans[wc].warplayers[rank-1].defends|length > 0  %}
                            {{ war.warclans[wc].warplayers[rank-1].defends|length }}
                        {% endif %}
                    </td>
                    <td>
                    </td>

                    <td>&nbsp;</td>        

                    {% for at in 0..1 %}
                        <td class="attack">
                            {% if war.warclans[wc].warplayers[rank-1] is defined   %}
                                {% if war.warclans[wc].warplayers[rank-1].attacks[at] is defined %}
                                    {{ war.warclans[wc].warplayers[rank-1].attacks[at].defender.rank }}.
                                    {{ war.warclans[wc].warplayers[rank-1].attacks[at].defender.player.name }}
                                    {{ war.warclans[wc].warplayers[rank-1].attacks[at].percent }}%
                                    {{ war.warclans[wc].warplayers[rank-1].attacks[at].stars }}
                                    {{ war.warclans[wc].warplayers[rank-1].attacks[at].time|date('H:i') }}
                                {% else %}
                                    {% if app.user and is_granted('ROLE_ADMIN') %}
                                        <a href="{{ path('warevent_new',{'attacker_id':war.warclans[wc].warplayers[rank-1].id} ) }}">---</a>
                                    {% else %}
                                        ---
                                    {% endif %}
                                {% endif %}
                            {% endif %}
                        </td>
                    {% endfor %}

                    <td>&nbsp;</td>

                {% endfor %}

                <td>&nbsp;</td>

            </tr>
        {% endfor %}

    </table>


<script type="text/javascript"
        src="https://www.google.com/jsapi?autoload={
        'modules':[{
        'name':'visualization',
        'version':'1',
        'packages':['corechart']
        }]
        }">
</script>

<script type="text/javascript">
    google.setOnLoadCallback(drawChart);

    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Time Remaining', '{{ war.warclans[0].clan.name }}', '{{ war.warclans[1].clan.name }}', 'nr att', 'nr att'],{% set lasthr = warevents[0] is defined ? warevents[0].time|date('H') : 0 %}{% for hr in 23..lasthr %}
            [[{{ hr }}, 0, 0],{{ war.warclans[1].timestars[hr] }} ,{{ war.warclans[0].timestars[hr] }} ,{{ war.warclans[1].timeattacks[hr] }} ,{{ war.warclans[0].timeattacks[hr] }} ],{% endfor %}
        ]);
        var options = {
            title: 'War Stars',
            legend: {position: 'bottom'},
            //hAxis: {format: 'KK:mm', viewWindowMode: 'maximized', viewWindow: {min: '23:00', max: '00:00'}, minValue: '23:00', maxValue: '00:00'},
            hAxis: {format: 'HH:mm', direction: -1, viewWindow: {min: [23, 0, 0], max: [0, 0, 0]}},
            vAxis: {minValue:0, maxValue:{{ war.size*3 }}, viewWindowMode: 'maximized'},
            seriesType: "line",
            series: {
                0: {type: "line", color: "blue"},
                1: {type: "line", color: "red"},
                2: {type: "area", color: "lightblue"},
                3: {type: "area", color: "orange"}
            }
        };
        var chart = new google.visualization.ComboChart(document.getElementById('chart_attacks'));
        chart.draw(data, options);

        var data = google.visualization.arrayToDataTable([
            ['stars', '{{ war.warclans[0].clan.name }}', '{{ war.warclans[1].clan.name }}'],{% for n in 3..0 %}
            ['{{ n }}',{{ results[0][n] }} ,{{ results[1][n] }} ],{% endfor %}
        ]);

        var view = new google.visualization.DataView(data);
        //view.setColumns([0, 1, {calc: "stringify", sourceColumn: 1, type: "string", role: "annotation"}, 2]);

        var options = {
            title: "Attacks per nr of Stars",
            bar: {groupWidth: "80%"},
            legend: {position: "none"},
        };
        var chart = new google.visualization.ColumnChart(document.getElementById("chart_stars"));
        chart.draw(view, options);
    }

</script>

<p>
<div id="chart_attacks" style="width: 640px; height: 320px; float:left"></div>
<div id="chart_stars" style="width: 640px; height: 320px; float:left"></div>
</p>





<table class="warevents">
    <tr><th colspan="7">War Events</th></tr>
    <tr>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
    </tr>

    {% for n in 0..war.size*4 %}
        {% if warevents[n] is defined %}
            <tr class="{{warevents[n].stars<=warevents[n].defender.stars(warevents[n].time)?'gray':warevents[n].attacker.warclan.clan.id==1?'green':'red'}}">

                {% if warevents[n].attacker.warclan.clan.id==1 %}

                    <td>
                        {{ warevents[n].attacker }}<br/>
                        {{ warevents[n].percent }}% <img height="10px" src="{{ asset( ['images/',warevents[n].stars,'star.png']|join ) }}">
                    </td>
                    <td> ---> </td>
                    <td>{{ warevents[n].defender }}<br/></td>

                {% else %}

                    <td>{{ warevents[n].defender }}<br/></td>
                    <td> <--- </td>
                    <td>{{ warevents[n].attacker }}<br/>
                        {{ warevents[n].percent }}% <img height="10px" src="{{ asset( ['images/',warevents[n].stars,'star.png']|join ) }}">
                    </td>

                {% endif %}

                <td><br>{{ warevents[n].time|date('H:i') }}</td>

            </tr>
        {% endif %}
    {% endfor %}

</table>

    
<h1>Rankings</h1>
    <table>
        <th>#</th>
        <th>#</th>
        <th>name</th>
        <th>Attack</th>
        <th>Defense</th>
        <th>total</th>
    </tr>
    <tr>
        <th></th><th></th><th></th>
        <!--
        <th>d1</th>
        <th>d2</th>
        <th>3*</th>
        <th>2*</th>
        <th>1*</th>
        <th>0*</th>
        <th>td</th>
        <th>ts</th>
        -->
        <th>score</th>
        <!--
        <th>3*</th>
        <th>2*</th>
        <th>1*</th>
        <th>0*</th>
        <th>td</th>
        <th>d</th>
        -->
        <th>score</th>
            {% set rank=0 %}
            {% for player in rankings %}
            {% set rank=rank+1 %}
        <tr>
            <td>{{ rank }}</td>
            <td>({{ player.pos }})</td>
            <td>{{ player.name }}</td>
            <!--
            <td>{{ player.adiff1 }}</td>
            <td>{{ player.adiff2 }}</td>
            <td>{{ player.astars3 }}</td>
            <td>{{ player.astars2 }}</td>
            <td>{{ player.astars1 }}</td>
            <td>{{ player.astars0 }}</td>
            <td>{{ player.atotdmg }}</td>
            <td>{{ player.atotstars }}</td>
            -->
            <td>{{ player.ascore }}</td>
            <!--
            <td>{{ player.dstars3 }}</td>
            <td>{{ player.dstars2 }}</td>
            <td>{{ player.dstars1 }}</td>
            <td>{{ player.dstars0 }}</td>
            <td>{{ player.dtotdmg }}</td>
            <td>{{ player.ddiff }}</td>
            -->
            <td>{{ player.dscore }}</td>

            <td>{{ player.tscore }}</td>
        </tr>
    {% endfor %}
</table>
{# dump(rankings) #}
{% endblock %}